package modelo;
// Generated 20-feb-2018 14:31:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String nombreEmp;
     private String oficinas;
     private Date fundacion;
     private Integer numeroEmpleados;
     private String contacto;
     private String presidente;
     private Set vacantes = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String nombreEmp, String oficinas, String contacto, String presidente) {
        this.nombreEmp = nombreEmp;
        this.oficinas = oficinas;
        this.contacto = contacto;
        this.presidente = presidente;
    }
    public Empresa(String nombreEmp, String oficinas, Date fundacion, Integer numeroEmpleados, String contacto, String presidente, Set vacantes) {
       this.nombreEmp = nombreEmp;
       this.oficinas = oficinas;
       this.fundacion = fundacion;
       this.numeroEmpleados = numeroEmpleados;
       this.contacto = contacto;
       this.presidente = presidente;
       this.vacantes = vacantes;
    }
   
    public String getNombreEmp() {
        return this.nombreEmp;
    }
    
    public void setNombreEmp(String nombreEmp) {
        this.nombreEmp = nombreEmp;
    }
    public String getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(String oficinas) {
        this.oficinas = oficinas;
    }
    public Date getFundacion() {
        return this.fundacion;
    }
    
    public void setFundacion(Date fundacion) {
        this.fundacion = fundacion;
    }
    public Integer getNumeroEmpleados() {
        return this.numeroEmpleados;
    }
    
    public void setNumeroEmpleados(Integer numeroEmpleados) {
        this.numeroEmpleados = numeroEmpleados;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getPresidente() {
        return this.presidente;
    }
    
    public void setPresidente(String presidente) {
        this.presidente = presidente;
    }
    public Set getVacantes() {
        return this.vacantes;
    }
    
    public void setVacantes(Set vacantes) {
        this.vacantes = vacantes;
    }




}


