package modelo;
// Generated 20-feb-2018 14:31:40 by Hibernate Tools 4.3.1



/**
 * ExperienciaLaboral generated by hbm2java
 */
public class ExperienciaLaboral  implements java.io.Serializable {


     private int idExperienciaLaboral;
     private Profesionista profesionista;
     private String empresa;
     private String cargo;
     private String periodo;

    public ExperienciaLaboral() {
    }

	
    public ExperienciaLaboral(int idExperienciaLaboral, String empresa, String cargo, String periodo) {
        this.idExperienciaLaboral = idExperienciaLaboral;
        this.empresa = empresa;
        this.cargo = cargo;
        this.periodo = periodo;
    }
    public ExperienciaLaboral(int idExperienciaLaboral, Profesionista profesionista, String empresa, String cargo, String periodo) {
       this.idExperienciaLaboral = idExperienciaLaboral;
       this.profesionista = profesionista;
       this.empresa = empresa;
       this.cargo = cargo;
       this.periodo = periodo;
    }
   
    public int getIdExperienciaLaboral() {
        return this.idExperienciaLaboral;
    }
    
    public void setIdExperienciaLaboral(int idExperienciaLaboral) {
        this.idExperienciaLaboral = idExperienciaLaboral;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


