package modelo;
// Generated 20-feb-2018 14:31:40 by Hibernate Tools 4.3.1



/**
 * FormacionAcademica generated by hbm2java
 */
public class FormacionAcademica  implements java.io.Serializable {


     private int idFormacionAcademica;
     private Profesionista profesionista;
     private String grado;
     private String periodo;

    public FormacionAcademica() {
    }

	
    public FormacionAcademica(int idFormacionAcademica, String grado, String periodo) {
        this.idFormacionAcademica = idFormacionAcademica;
        this.grado = grado;
        this.periodo = periodo;
    }
    public FormacionAcademica(int idFormacionAcademica, Profesionista profesionista, String grado, String periodo) {
       this.idFormacionAcademica = idFormacionAcademica;
       this.profesionista = profesionista;
       this.grado = grado;
       this.periodo = periodo;
    }
   
    public int getIdFormacionAcademica() {
        return this.idFormacionAcademica;
    }
    
    public void setIdFormacionAcademica(int idFormacionAcademica) {
        this.idFormacionAcademica = idFormacionAcademica;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


