package modelo;
// Generated 20-feb-2018 14:31:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesionista generated by hbm2java
 */
public class Profesionista  implements java.io.Serializable {


     private String correo;
     private String carrera;
     private String nacionalidad;
     private String contrasena;
     private String telefono;
     private String nombre;
     private Set vacantes = new HashSet(0);
     private Set experienciaLaborals = new HashSet(0);
     private Set skillses = new HashSet(0);
     private Set formacionAcademicas = new HashSet(0);

    public Profesionista() {
    }

	
    public Profesionista(String correo, String nacionalidad, String contrasena, String telefono) {
        this.correo = correo;
        this.nacionalidad = nacionalidad;
        this.contrasena = contrasena;
        this.telefono = telefono;
    }
    public Profesionista(String correo, String carrera, String nacionalidad, String contrasena, String telefono, String nombre, Set vacantes, Set experienciaLaborals, Set skillses, Set formacionAcademicas) {
       this.correo = correo;
       this.carrera = carrera;
       this.nacionalidad = nacionalidad;
       this.contrasena = contrasena;
       this.telefono = telefono;
       this.nombre = nombre;
       this.vacantes = vacantes;
       this.experienciaLaborals = experienciaLaborals;
       this.skillses = skillses;
       this.formacionAcademicas = formacionAcademicas;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getVacantes() {
        return this.vacantes;
    }
    
    public void setVacantes(Set vacantes) {
        this.vacantes = vacantes;
    }
    public Set getExperienciaLaborals() {
        return this.experienciaLaborals;
    }
    
    public void setExperienciaLaborals(Set experienciaLaborals) {
        this.experienciaLaborals = experienciaLaborals;
    }
    public Set getSkillses() {
        return this.skillses;
    }
    
    public void setSkillses(Set skillses) {
        this.skillses = skillses;
    }
    public Set getFormacionAcademicas() {
        return this.formacionAcademicas;
    }
    
    public void setFormacionAcademicas(Set formacionAcademicas) {
        this.formacionAcademicas = formacionAcademicas;
    }




}


