package modelo;
// Generated 20-feb-2018 14:31:40 by Hibernate Tools 4.3.1



/**
 * Skills generated by hbm2java
 */
public class Skills  implements java.io.Serializable {


     private SkillsId id;
     private Profesionista profesionista;
     private int skillgrado;

    public Skills() {
    }

    public Skills(SkillsId id, Profesionista profesionista, int skillgrado) {
       this.id = id;
       this.profesionista = profesionista;
       this.skillgrado = skillgrado;
    }
   
    public SkillsId getId() {
        return this.id;
    }
    
    public void setId(SkillsId id) {
        this.id = id;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public int getSkillgrado() {
        return this.skillgrado;
    }
    
    public void setSkillgrado(int skillgrado) {
        this.skillgrado = skillgrado;
    }




}


