package modelo;
// Generated 20-feb-2018 14:31:40 by Hibernate Tools 4.3.1



/**
 * SkillsId generated by hbm2java
 */
public class SkillsId  implements java.io.Serializable {


     private String correo;
     private String skillnombre;

    public SkillsId() {
    }

    public SkillsId(String correo, String skillnombre) {
       this.correo = correo;
       this.skillnombre = skillnombre;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getSkillnombre() {
        return this.skillnombre;
    }
    
    public void setSkillnombre(String skillnombre) {
        this.skillnombre = skillnombre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SkillsId) ) return false;
		 SkillsId castOther = ( SkillsId ) other; 
         
		 return ( (this.getCorreo()==castOther.getCorreo()) || ( this.getCorreo()!=null && castOther.getCorreo()!=null && this.getCorreo().equals(castOther.getCorreo()) ) )
 && ( (this.getSkillnombre()==castOther.getSkillnombre()) || ( this.getSkillnombre()!=null && castOther.getSkillnombre()!=null && this.getSkillnombre().equals(castOther.getSkillnombre()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCorreo() == null ? 0 : this.getCorreo().hashCode() );
         result = 37 * result + ( getSkillnombre() == null ? 0 : this.getSkillnombre().hashCode() );
         return result;
   }   


}


