package modelo;
// Generated 20-feb-2018 14:31:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vacante generated by hbm2java
 */
public class Vacante  implements java.io.Serializable {


     private int idVacante;
     private Empresa empresa;
     private String horario;
     private String lugar;
     private double salario;
     private String puesto;
     private String descripcion;
     private Set profesionistas = new HashSet(0);

    public Vacante() {
    }

	
    public Vacante(int idVacante, String lugar, double salario, String puesto) {
        this.idVacante = idVacante;
        this.lugar = lugar;
        this.salario = salario;
        this.puesto = puesto;
    }
    public Vacante(int idVacante, Empresa empresa, String horario, String lugar, double salario, String puesto, String descripcion, Set profesionistas) {
       this.idVacante = idVacante;
       this.empresa = empresa;
       this.horario = horario;
       this.lugar = lugar;
       this.salario = salario;
       this.puesto = puesto;
       this.descripcion = descripcion;
       this.profesionistas = profesionistas;
    }
   
    public int getIdVacante() {
        return this.idVacante;
    }
    
    public void setIdVacante(int idVacante) {
        this.idVacante = idVacante;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProfesionistas() {
        return this.profesionistas;
    }
    
    public void setProfesionistas(Set profesionistas) {
        this.profesionistas = profesionistas;
    }




}


